theme: jekyll-theme-minimal
title: [Basak Kocaoglu]
description: [(If the lights in the above pic also makes you think that hacking it to play Conway's Game of Life 
<a href="https://www.adafruit.com/product/89" style="color: blue; text-decoration: underline;">(as in)</a> would be fun... 
please do reach out to me :) )]
logo: assets/img/imgg.png
include: ["_pages"]

plugins:
  - jekyll-gist
