theme: jekyll-theme-minimal
title: Basak Kocaoglu
description: [in progress]
logo: assets/img/imgg.png
include: ["_pages"]

plugins:
  - jekyll-gist

 <!-- (If the lights above also makes you think that it could play Conway's Game of Life 
(as in adafruit.com/product/89)... 
please do reach out :) ) 

 [(Twitter)](https://x.com/basak__k)

 <a href="https://scholar.google.com/citations?user=LGUid5IAAAAJ&hl=en"> Google Scholar</a>
 
 -->
