theme: jekyll-theme-minimal
title: Basak Kocaoglu
description: [
basak.kocaoglu (at) kcl.ac.uk 
b.kocaoglu24 (at) imperial.ac.uk ]
logo: assets/img/IMG_4588 3.jpg
include: ["_pages"]

plugins:
  - jekyll-gist

