theme: jekyll-theme-minimal
title: Basak Kocaoglu
description: [
basak.kocaoglu (at) kcl.ac.uk 
b.kocaoglu24 (at) imperial.ac.uk ]
logo: assets/img/1722065777975.jpeg
include: ["_pages"]

plugins:
  - jekyll-gist

